version: '3.9'

networks:
  storages:
  public:

volumes:
  clickhouse:
    name: ${CLICKHOUSE_DOCKER_MOUNT}
  mysql:
    name: ${MYSQL_DOCKER_MOUNT}
  

services:

  # Supported storages.
  clickhouse:
    image: yandex/clickhouse-server:${CLICKHOUSE_VERSION}
    ports:
      - ${CLICKHOUSE_EXTERNAL_PORT}:${CLICKHOUSE_INTERNAL_PORT}
    volumes:
      - clickhouse:/var/lib/clickhouse:rw
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    networks:
      - storages

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}
    volumes:
      - mysql:/var/lib/mysql:rw
      - ./etc/my.cnf:/etc/my.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - storages
  
  # Data comsumers
  clickhouse_writer:
    image: clickhouse-writer:${CLICKHOUSE_WRITER_VERSION}
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
      args:
        - STORAGE=clickhouse
        - SERVICE=writer
    restart: unless-stopped
    networks:
      - storages
      - public
    depends_on:
      - clickhouse
    command: >
      -endpoint '0.0.0.0:24190'
      -host '${CLICKHOUSE_WRITER_HOST}'
      -port ${CLICKHOUSE_WRITER_PORT}
      -user '${CLICKHOUSE_WRITER_USER}'
      -password '${CLICKHOUSE_WRITER_PASSWORD}'
      -workers ${CLICKHOUSE_WRITER_WORKERS}
      -log '${CLICKHOUSE_WRITER_LOG_LEVEL}'
  
  mysql_writer:
    image: mysql-writer:${MYSQL_WRITER_VERSION}
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
      args:
        - STORAGE=mysql
        - SERVICE=writer
    restart: unless-stopped
    networks:
      - storages
      - public
    depends_on:
      - mysql
    command: >
      -endpoint '0.0.0.0:24190'
      -host '${MYSQL_WRITER_HOST}'
      -port ${MYSQL_WRITER_PORT}
      -user '${MYSQL_WRITER_USER}'
      -password '${MYSQL_WRITER_PASSWORD}'
      -workers ${MYSQL_WRITER_WORKERS}
      -log '${MYSQL_WRITER_LOG_LEVEL}'
  
  # Data providers
  clickhouse_reader:
    image: clickhouse-reader:${CLICKHOUSE_READER_VERSION}
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
      args:
        - STORAGE=clickhouse
        - SERVICE=reader
    restart: 'no'
    networks:
      - storages
      - public
    depends_on:
      - clickhouse_writer
    command: >
      -comsumer '${CLICKHOUSE_READER_CONSUMER}'
      -host '${CLICKHOUSE_READER_HOST}'
      -port ${CLICKHOUSE_READER_PORT}
      -user '${CLICKHOUSE_READER_USER}'
      -password '${CLICKHOUSE_READER_PASSWORD}'
      -from '${CLICKHOUSE_READER_FROM}'
      -to '${CLICKHOUSE_READER_TO}'
      -order '${CLICKHOUSE_READER_ORDER}'
      -batch ${CLICKHOUSE_READER_BATCH}
      -window "${CLICKHOUSE_READER_WINDOW}"
      -workers ${CLICKHOUSE_READER_WORKERS}
      -log '${CLICKHOUSE_READER_LOG_LEVEL}'
  
  mysql_reader:
    image: mysql-reader:${MYSQL_READER_VERSION}
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
      args:
        - STORAGE=mysql
        - SERVICE=reader
    restart: 'no'
    networks:
      - storages
      - public
    depends_on:
      - mysql_writer
    command: >
      -comsumer '${MYSQL_READER_CONSUMER}'
      -host '${MYSQL_READER_HOST}'
      -port ${MYSQL_READER_PORT}
      -user '${MYSQL_READER_USER}'
      -password '${MYSQL_READER_PASSWORD}'
      -from '${MYSQL_READER_FROM}'
      -to '${MYSQL_READER_TO}'
      -order '${MYSQL_READER_ORDER}'
      -batch ${MYSQL_READER_BATCH}
      -window "${MYSQL_READER_WINDOW}"
      -workers ${MYSQL_READER_WORKERS}
      -log '${MYSQL_READER_LOG_LEVEL}'
    
    
